### ISSUE TITLE
displaylink-driver fails to understand kernel version correctly

### ISSUE THREAD

**Issue by LordWolfer** [DisplayLink/evdi#1]
I'm not sure whether this is the right forum to report this, but when I tried to install the displaylink-driver (as per this guide: http://support.displaylink.com/knowledgebase/articles/615714#ubuntu) I'm getting a script error saying that my kernel is too old (even though it's a rather new one). Script output:

> Verifying archive integrity... All good.
> Uncompressing DisplayLink Linux Driver 1.0.68  100%  
> DisplayLink Linux Software 1.0.68 install script called: install
> Distribution discovered: Debian GNU/Linux unstable (sid)
> Unsatisfied dependencies. Missing component: Kernel version 4.1.0-1-amd64 is too old. At least 3.14 is required.
> This is a fatal error, cannot install DisplayLink Linux Software.

It's probably because the script only checks minor versions instead of checking both major and minor, and should be easy to fix.

**Comment by displaylink-mlukaszek** [comment]
Thanks for the report - we are aware of this problem and it will be fixed in next releases.

I am closing this issue - this project will only be accepting reports for open-source components of the driver - evdi and libevdi. To report issues in DisplayLink Ubuntu driver, please use our forum at http://displaylink.org/forum/forumdisplay.php?f=29

Thanks,
Michal
