### ISSUE TITLE
Linux 4.15 already ships the drm_file*

### ISSUE THREAD

**Issue by mar77i** [DisplayLink/evdi#117]
...which means I'll have to apply this patch to make the bulid work. Please do some research on version numbers before adding these preprocessor checks.

```
diff --git a/module/evdi_connector.c b/module/evdi_connector.c
index 811b85a..69a98b9 100644
--- a/module/evdi_connector.c
+++ b/module/evdi_connector.c
@@ -85,7 +85,7 @@ static struct drm_encoder *evdi_best_single_encoder(struct drm_connector
        int enc_id = connector->encoder_ids[0];

        return drm_encoder_find(connector->dev,
-#if KERNEL_VERSION(4, 16, 0) <= LINUX_VERSION_CODE
+#if KERNEL_VERSION(4, 15, 0) <= LINUX_VERSION_CODE
                                 NULL,
 #endif
                                 enc_id);
```

**Comment by dawikur** [comment]
Yep, this is my typo, should be '4, 15' from the start.

**Comment by Unaccounted4** [comment]
How long would this take to be released in an updated displaylink driver package?

**Comment by mar77i** [comment]
You can apply the patch yourself if you use any DKMS package, because these are built to the current kernel at hand. It's simple enough, really.

**Comment by Unaccounted4** [comment]
It is easy. Just a pain to manage when you have over 200 Dell D1000 and a CTO shouting at you about "Spectre and Meltdown security concerns".

It'd be easier for my use case to have them bundled up.

**Comment by RyanNerd** [comment]
Sorry a bit of a c++ noob here. How the #@$%& do I get this to work with 4.15 kernel. No idea how to patch and I'd rather not build from source, but will if I need to.

**Comment by cacarr-pdxweb** [comment]
I'm with RyanNerd -- lost my secondary display with 4.15. Currently not pleased.

**Comment by zachzundel** [comment]
Hi @RyanNerd and @cacarr-pdxweb -- I'm not sure which OS you're running, but I got it working on Arch by cloning the evdi-git repository from the AUR, adding the patch for PR #118 to the PKGBUILD, and then installing that. If either of you need more help doing that, I'd be happy to assist.

**Comment by RyanNerd** [comment]
Thanks @zachzundel I'm running Linux Mint 18.2. I got it working by thunking my kernel down to 4.14.19 and running the DisplayLink script while running on that kernel. The script executed without issues. On a whim I installed the new 4.15.4 kernel and for some reason **DisplayLink worked** without the need to run the script against the new kernel. I hope this helps you @cacarr-pdxweb 
The main challenge I had was getting the nouveau drivers working (DisplayLink will not work with NVida's proprietary drivers) -- since every SO or other web page when searching for "nouveau" tell you how to **disable** it and not how to get the ^#$% nouveau driver to actually work -- I still have no idea how I got nouveau to start working...

**Comment by zachzundel** [comment]
I don't think this is an issue with the displaylink package, but with the EVDI package, which DisplayLink depends on. There is already a PR that solves this issue, all that needs to happen is a maintainer merging that into master and then installing `evdi-git` from the AUR should fix it.

**Comment by mar77i** [comment]
Is this even related?
