### ISSUE TITLE
Ubuntu 18.04 LTS session crash on connect

### ISSUE THREAD

**Issue by petrleocompel** [DisplayLink/evdi#128]
As Ubuntu 18.04 LTS is now out and available for download i would expect somebody would try install an use it with evdi. 

I expected issue with kernel 4.15 #117 so i'm using 4.16.7. 
For complete story - i was upgrading from Ubuntu 16.04.3 LTS with kernel 4.8. 
As first thing Ubuntu after upgrade started session with Wayland and as wayland is not supported yet i hope something is happening. But it looks quite dead. #58 

2 GPUs in my ntb -  Nvidia + Intel. Primary is Intel.

Tryed to be step a head so.

Reffering to - #114
If evdi is connected on boot i cannot start session at all and on login will freeze whole system.
If device is connected faster session started, after few seconds session will crash. Log attached to [pastebin](https://pastebin.com/eJq0dWzg).
After that login screen is not able to start session.
[https://pastebin.com/eJq0dWzg](https://pastebin.com/eJq0dWzg)

Reffering to - #80 
Allow me to start X but evdi displays are not working.

**Comment by MatthewBooth** [comment]
Ubuntu 18.04 does not use Wayland as default, the default is still Xorg and this is due to stability.

I'm running Ubuntu 18.04 and using the latest DisplayLink driver (4.2, at time of writing) without an issue.

Some caveats:
- Kernel 4.15.0-20-generic  at time of writing
- HP Zbook 15 G3
- Intel and AMD FirePro
- I'm running just the Intel driver (AMD drivers are not installed)
- dmesg is clean of errors (minus a bluetooth issue I don't care about)

I didn't do anything special. I just installed the driver and the connected displays started up. It works when disconnected and reconnected without an issue (something that was a problem on 16.04.4 LTS) and I can connect everything, then boot the laptop, and everything works.

I know this doesn't help your issue, but it might help to hear from someone on the same OS version who's not having any issues.

CPU usage is STILL ridiculously high given that the box is supposed to do processing. I measured in `top` the DisplayLinkManager process consuming "105%" CPU usage when simply highlighting text and waving my mouse around.

In Windows this is literally 3-5%.

**Comment by petrleocompel** [comment]
Fact that Ubuntu 18.0 does not use Wayland as default I know, but after upgrade default session was Wayland. Just saying.

That fact about CPU high load usage is known. Well, I'm experiencing that bug from first versions. Reffering on actual separate issue -> #126.
In OSX (MacOS) is little bit higher for me 8-15%.

Well, maybe system reinstallation could solve issue but that is not a good way how to solve issue. 

So I will wait for anybody who could found anything suspicious in log or have some idea what should I try to make it work correctly.

**Comment by MatthewBooth** [comment]
Yeah it'll have been Wayland for sure if you went the `dist-upgrade` process, as that takes you through 17.04->18.04 and Wayland being the default in 17.04 (colleague experienced that same issue the other day).

I agree with you, a full installation is a terrible way to solve the problem. I just thought you might take solace in knowing that between where you were, and where I am, there's a solution somewhere in the middle!

**Comment by MatthewBooth** [comment]
`cat /usr/share/gnome/gnome-version.xml `
```xml
<?xml version="1.0" encoding="UTF-8"?>
<gnome-version>
 <platform>3</platform>
 <minor>28</minor>
 <micro>1</micro>
 <distributor>Ubuntu</distributor>
</gnome-version>
```
`sudo X -version`
```
X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-119-generic x86_64 Ubuntu
Current Operating System: Linux MattBooth-Ubuntu 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-20-generic root=UUID=1311b6bc-9963-46ff-9822-aff09e8b68ed ro quiet splash vt.handoff=1
Build Date: 13 April 2018  08:07:36PM
xorg-server 2:1.19.6-1ubuntu4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

Just in case those help you. There seemed to be a lot of gnome session errors with X in your logs.

**Comment by petrleocompel** [comment]
I was upgrading from 16.04.3 directly to 18.04 (LTS to LTS upgrade). So, I have no idea why it changed default to Wayland.

I have a same gnome and X server versions.

If you mean those gdm-session erorrs I think those errors are forwareded from X.Org and unfortunately errors like `Segmentation fault at address 0x8` doesn't helped me at all. :confused:.

**Comment by dawikur** [comment]
Is the problem still there even when not using Wayland?

Can you try to force `modesetting` driver?
To do this, as a root user create a file `20-displaylink.conf` under:
`/usr/share/X11/xorg.conf.d/`

with the following content: 
```bash
Section "Device"
  Identifier "DisplayLink"
  Driver     "modesetting"
EndSection  
```

A reboot is required for the setting to be effective.

**Comment by displaylink-dkurek** [comment]
Will close the issue for now as there was no response or any other activity.
If you still see the problem please first check support page
(https://support.displaylink.com/), there are some things to try.
