### ISSUE TITLE
Poor performance Archlinux Linux 5.12.15-zen1-1 - AMD Ryzen 5 3500U Asus Vivobook X412D

### ISSUE THREAD

**Issue by kython28** [DisplayLink/evdi#293]
* Archlinux
  * Linux 5.12.15.zen1-1
  * Xorg version 1.20.12-1
  * Gnome
  * AMD Ryzen 5 3500U - Radeon Vega Graphics

All the displays that I connect with evdi present a very bad performance, barely usable :-(
I have checked if it is my PC, and fortunately not, in Windows 10 it works perfect.

https://user-images.githubusercontent.com/23725145/125177757-151c6280-e1a4-11eb-8cf5-489f45b37c7f.mp4

**Comment by TheBITLINK** [comment]
Hi, unfortunately this is a common issue with integrated AMD GPU drivers, but right now you can try 2 workarounds (each one with their own set of problems though):

### Workaround 1

 If you're using the latest git version (which I assume you are, since you're using Arch as well), add the following line to `/etc/modprobe.d/evdi.conf` (create the file if it doesn't exist):
 ```
options evdi disable_texture_import=1
```
This workaround will disable direct GPU access (which is buggy in AMD systems anyways) and fallback to a CPU only method. You will have a slightly increased CPU usage (nothing too bad though), but you'll not experience any more lag unless the system is under very heavy load.
The two downsides are:
 - The fallback only works on GNOME Wayland, since it relies on a behavior specific to mutter when running in Wayland mode.
 - You *might* experience random GPU driver crashes (this one is not as consistent and varies depending on your hardware setup, many have reported it doesn't happen to them, but in my case it happened a lot, also with a 3500U). Give it a try though, it might work for you

### Workaround 2

If you're experiencing GPU driver crashes, or want to user another DE that isn't GNOME, try this (very unstable) patch:

https://github.com/pioto1225/evdi/tree/amd_vmap_texture

This one bypasses the internal copy the GPU driver makes and uses a faster approach, but does so in a very hacky way.
It works pretty well though, as long as you don't disconnect or turn off any of the displaylink screens. The moment you do so, you have a 50/50 chance of getting a kernel panic.

If you intend to use you additional displays for large amounts of time, this might be the best option since you'll not have the random GPU drivers crashes. The system will only crash if you disconnect one of the displays. This workaround also works with other DEs and even Xorg (I've personally only tried KDE though)

---

The root problem seems to be in the AMD driver, as far as I know. Until a proper fix is made or a better workaround is found, those are the only 2 options for AMD systems.
