### ISSUE TITLE
Ubuntu 22.04: sudo modprobe evdi failed: ERROR: could not insert 'evdi': Exec format error

### ISSUE THREAD

**Issue by ahmedrayhan** [DisplayLink/evdi#366]
* Are you using the latest driver?
yes. its 5.6
  * Are you using the latest EVDI version?
yes. 1.11.0
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    yes
  * Is this issue related to evdi/kernel?
   yes
  * Ubuntu 22.04

  * Linux kernel 5.15.0-40-generic
  
I have installed Ubuntu 22.04 and installed the latest release of displaylink driver 5.6. Installation finished okay but the driver is not working. I see the following error.

```
module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 000000001c54c643, val ffffffffc1f44651
modprobe: ERROR: could not insert 'evdi': Exec format error

```
Am I missing something? Please advise..

**Comment by ahmedrayhan** [comment]
its very similar to #301

**Comment by johannes-mueller** [comment]
I had the same problem. It was somehow due to incompatible kernel headers. I uninstalled all the `linux-headers-*` packages and then reinstalled the one of my current kernel version `5.13.0-52-generic`. Then I uninstalled DisplayLink, reinstalled it. Then it worked.

We will see if this survives the next kernel update.

**Comment by ahmedrayhan** [comment]
already tried that but didn't work

**Comment by ahmedrayhan** [comment]
this https://github.com/DisplayLink/evdi/issues/215#issuecomment-889771551 worked
