### ISSUE TITLE
How to update driver

### ISSUE THREAD

**Issue by JumpLink** [DisplayLink/evdi#47]
I I would like update the driver from 1.1.61 to 1.2.58 but get this warning:

```
Verifying archive integrity... All good.
Uncompressing DisplayLink Linux Driver 1.2.58  100%  
DisplayLink Linux Software 1.2.58 install script called: install
Distribution discovered: Ubuntu 16.04.1 LTS
WARNING: Version 1.1.61 of EVDI kernel module is already running.
Please reboot before attempting to re-install DisplayLink Linux Software.
Installation terminated.
```

After reboot I run the setup again and get the same warning, do I neet to uninstall the driver before by self?

**Comment by displaylink-mlukaszek** [comment]
This question is actually DisplayLink driver specific so should be asked on the support page or the forum, but I'll answer here anyway.

Before attempting to install a newer version of never evdi (which is one of the components DisplayLink Ubuntu Driver would install), older evdi must be gone - and unloaded from the memory. Because evdi cannot be unloaded while it's used by X, you must uninstall the previous version (in case of full DL driver package call: `sudo displaylink-installer uninstall`), then reboot to make sure evdi is not in loaded, then install the newer version.

BTW, the newest version of DL Ubuntu Driver at the moment is 1.2.65.

**Comment by displaylink-mlukaszek** [comment]
Closing (assuming further comments, if any, will be on DisplayLink Forum)

**Comment by matt-the-wizard** [comment]
:+1:
