### ISSUE TITLE
Cursor visibly slow when primary (laptop) screen closed, without glitches when open (Ubuntu 16.04, Ubuntu 16.10)

### ISSUE THREAD

**Issue by nekromoff** [DisplayLink/evdi#61]
Laptop + DisplayLink adapter + external monitor 
Unified display (e.g. screen mirroring) 1920x1080

Cursor movement is visibly slow (tearing) when primary screen (laptop) is closed/turned off (.e.g with lid closed). When laptop screen is on (lid open) cursor is behaving normally (fast, no tearing) as it is by default on laptop screen only.

CPU usage of DisplayManager does not seem to vary between these two.

**Comment by nekromoff** [comment]
btw, the latest 1.2.65 07 Oct 2016 drivers used

**Comment by displaylink-mlukaszek** [comment]
Having the laptop lid closed makes X do really weird things when two graphics adapters are used. Sadly, the best workaround is to keep the lid opened.

**Comment by nekromoff** [comment]
Bug still in the latest version evdi drivers

**Comment by zachzundel** [comment]
Could I get some more information on how this comes from X? I would like to take a crack at addressing this.

**Comment by nekromoff** [comment]
Sorry, I have stopped using this adapter and instead opted for USB-C original by Dell that now works fine with the latest Linux kernels.

**Comment by gpanders** [comment]
I am still seeing this issue with the newest DisplayLink driver released in June

**Comment by lpjiang97** [comment]
Having this issue, too. Anyone came up with a solution?

**Comment by piccaruse** [comment]
Having this issue aswell running 2 screens, don't know if this is related but I'm getting this spam in dmesg

`[ 2873.707859] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0xab, supported mask 0x7400003f
[ 2873.707876] [drm:drm_wait_vblank [drm]] *ERROR* Unsupported type value 0x40000aa, supported mask 0x7400003f
`

**Comment by piccaruse** [comment]
No workarounds or fixes regarding the actual issue of slow displays when the laptop screen is disabled? :)

**Comment by bartziengs** [comment]
I'm experiencing the same on my notebook with Nvidia/intel shared graphics on ElementaryOS Loki. Altough I forced Xserver to use my intel drivers instead of nvidia (otherwise it wouldn't work) i'm having exactly the same as described above.

**Comment by compuguy** [comment]
@displaylink-mlukaszek Yes, that helps with redirecting syslog log spam, but Performance is still poor when the onboard display is off (laptop; shut lid), with the latest ubuntu driver release, on Ubuntu 16.04.

**Comment by piccaruse** [comment]
I recorded this short video to show the differences https://github.com/DisplayLink/evdi/issues/61 also seems to be more reports of this at http://displaylink.org/forum/showthread.php?p=84445#post84445

**Comment by gnutix** [comment]
I have the slow cursor/lag too but with the laptop lid open too. Dell XPS 13 Developer edition, DisplayLink driver 1.4.210, Linux Mint 18.2 Sonya.

**Comment by tuxick** [comment]
Same issue when i disable laptop screen on asus zenbook UX430UA. i915 graphics/driver on Ubuntu 1804 kde/neon.

**Comment by praul** [comment]
same issues with latest evdi and displaylink from aur on manjaro 5.3rc7, i915

**Comment by lapsio** [comment]
i don't want to give crappy advices but disabling gpu accelerated compositing and going full software seems to reduce performance hit when lid is closed

**Comment by zdmitchell** [comment]
Any solutions to this? I'm having the same issue on my 2020 xps developer edition.

**Comment by ramon-kramer** [comment]
same issue here, Ubuntu 18.04 with latest displaylink drivers

**Comment by kseinitzer** [comment]
same issue here, Ubuntu 20.04.1 with latest DisplayLink drivers.

**Comment by heinrichreimer** [comment]
Also experiencing the same issue on Ubuntu 20.04.1.
This is a rather frustrating bug, but for now, I'll just keep the lid open.

**Comment by moritzknorr** [comment]
At all who are experiencing the issue on 20.04.: This helped me fix it:
https://displaylink.org/forum/showthread.php?p=90093
https://askubuntu.com/questions/1300775/ubuntu-20-04-displaylink-patch-for-xorg

**Comment by displaylink-emajewsk** [comment]
A fix for this has been merged to Xorg master a few weeks ago. It should be coming to Ubuntu soon.

**Comment by qwertycody** [comment]
+1 on this issue for myself running on Ubuntu 20.04.

I've been periodically updating my OS but so far this issue is still prevalent for myself.

@displaylink-emajewsk - I echo @martincox in regards to accountability that this bug is truly fixed - can we please have a link to the bug report?

I will try out the Xorg custom package and provide feedback as well.

Laptop is a [Dell Inspiron 15 3000 running a i7 with Intel Graphics](https://www.dell.com/en-us/shop/dell-laptops/inspiron-15-3000-laptop/spd/inspiron-15-3511-laptop).

![image](https://user-images.githubusercontent.com/4968312/144234533-6a7a06cc-49b1-429f-8315-92187e3d503f.png)

**Comment by qwertycody** [comment]
UPDATE - That link is actually dead on the forum post that was linked above by @moritzknorr

I guess I'll try updating all my packages on Ubuntu and see if anything that hits the wall actually fixes it.

**Not entirely confident about it considering this was a FRESH install of Ubuntu 20.04 as of October 6th 2021 that I updated many times before actually jumping into using it.**

Reference - I started a new job that day and needed to jump into using Linux full time for the type of Software Development work I'd be doing - naturally I've used DisplayLink adapters flawlessly for years (on Windows) so it came as a shock to me that something so glaringly obvious is a problem in a major distribution like Ubuntu.

- Display Link Forum Post:
    - https://displaylink.org/forum/showthread.php?p=90093

- Dead Link on the Forum Post:
    - https://www.displaylink.com/downloads/file?d=310

![image](https://user-images.githubusercontent.com/4968312/144235706-a7ba4cea-d634-497d-84eb-ee2f1b2db999.png)

**Comment by qwertycody** [comment]
I retract my statements above but am leaving them for the sake of context.

I've added an extensive comment on Canonical's Bug Tracker entry for Ubuntu.

If I'm reading all of this correctly and I didn't glance over an important detail - the bug is actually fixed and it's source is NOT DisplayLink but instead the maintainers of XServer due to unexpected impact of changes upstream.

In the event that someone over at Canonical deletes my comment I'm copy pasting it here as well.

https://bugs.launchpad.net/xorg-server/+bug/1875015?comments=all

> After doing some deeper reading I've come across this bug via the DisplayLink GitHub Repo.
> 
> As a developer, I recognize that this isn't really the responsiblity of the Canonical Ltd. to hunt down issues that don't relate back to the Core OS - to an extent - so it's not really THEIR fault that an unexpected side-effect was introduced in XServer.
> 
> That being said, DisplayLink and their "external graphics card" platform powers an overwhelming majority of Home and Office Docking Stations, Conference Rooms, Backpack Adapters, etc.
> 
> Ultimately frustrated end-users who don't care to dig deep into what the true issue is (including software developers) will give up and just blame Ubuntu and revert to the excuse "Linux is unstable and not a daily operating system"
> 
> I personally think this is a bad look for Canonical and Ubuntu and will cause a loss in market share due to reduced confidence in the stability of the platform.
> 
> Basically what I'm saying is - things like this that are glaringly obvious to end-users from the frontend perspective absolutely need to be prioritized and I hope that someone sees this and attempts to get this bug ultimately closed out.
> 
> This bug has been open since 2020-04-25.
> 
> I am writing this comment as of 2021-12-01.
> 
> The bug located over at XServer looks to be closed as of 2020-5-29 - though it's unclear to me if it's completely merged into main.
> 
> The two teams need to come together and figure this out because like I said previously - this is an extremely bad look from an end-user perspective and just adds to the invalid argument used for years that people use to complain about Linux instability.
> 
> My Comment on DisplayLink GitHub:
> - https://github.com/DisplayLink/evdi/issues/61#issuecomment-983603462
> - I am on a FRESH install of Ubuntu 20.04 as of October 6th 2021 that I updated many times before actually jumping into using it.
> - Reference - I started a new job that day and needed to jump into using Linux full time for the type of Software Development work I'd be doing - naturally I've used DisplayLink adapters flawlessly for years (on Windows) so it came as a shock to me that something so glaringly obvious is a problem in a major distribution like Ubuntu.
> 
> XServer Bug Tracker (Closed):
> - https://gitlab.freedesktop.org/xorg/xserver/-/issues/1028

**Comment by qwertycody** [comment]
My last spam comment on this - sincerely I'm profusely sorry for blowing everyone's inbox up over this.

**If you are still impacted by this issue and are running Ubuntu 18 or higher**

1. Navigate to - https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1875015
2. If you don't have an account on Ubuntu One / launchpad.net - create one
3. Get signed in
4. Click the Tiny Fire Button so the priority is raised - doing this will send a clear message to Canonical Project/Product Managers that this needs to be prioritized because everything that is done from a development perspective is done based on priority (only so many hours in a day and people who know how to do the specific task)
5. If you aren't sure please read my annotated screenshot below

![image](https://user-images.githubusercontent.com/4968312/144241767-17897ce5-7b8e-4d03-bf2f-689079a6befe.png)

**Comment by displaylink-emajewsk** [comment]
@qwertycody Thanks for taking the time to provide this guide. We don't have a direct line of communication with Canonical, so this is the only way the fix gets pushed.
