### ISSUE TITLE
Kernel 4.9 and fedora 25 with dual graphics. 

### ISSUE THREAD

**Issue by ment0s** [DisplayLink/evdi#70]
I got evdi compiled from source, displaylink manager running. 
When first plugged in = gnome restarts
Login again = display loads
Two displays connected to displaylink adapter are displaying black background. I can see cursor moving on those screens. Changing resolution to lower displays wallpaper and thats it. Also changing screen layout breaks one of the screens ( freeze) .

https://paste.fedoraproject.org/528840/60098148/ LOG. 

I have tested it under pure openbox and does the same so its not gnome.

**Comment by displaylink-mlukaszek** [comment]
Bear in mind that Linux releases should generally stay with "master" branch, not devel. Devel is not guaranteed to stay API-compatible with DLM binary for Ubuntu at all times - although it usually is, if not stated otherwise in release notes on GitHub.

Problem with plugging in for the first time is a Xorg crash - see https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1627852

What driver are you using for your graphics card?

**Comment by ment0s** [comment]
its ok, I have actually buolt from source that ships with official ubuntu displaylink ( th enewest one) O have just tried the release for 4.9 and has the same issue. ( I am not too concerned with X crash ) I just want to get my screens to work :)

I am using nouvaeu ( or whatever its called ) driver.

**Comment by displaylink-mlukaszek** [comment]
It's probably the right moment to move to DisplayLink's forum not here, as you kind of confirmed that evdi itself is fine (your screens show _something_). While adding a post on the forum, make sure that you attach DisplayLink logs that would provide more info about your setup. Some photos or a short video would also help. Thanks!
