### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by tobimensch** [DisplayLink/evdi#94]
Hello,

I'm thinking about buying a displaylink device to run it under Linux.

Here're a few questions. If this is the wrong place for those questions, then I'm sorry.

1) Can you use xrandr to disable/enable/configure the display like you'd do with a normal
display port?

2) Do displaylink display ports support standard EDID/ddc/i2c protocols, so that tools such
as ddccontrol and ddcutil can be used to change and read monitor settings on the fly?

3) Does displaylink result in increased CPU usage even when the image on the displaylink
screen is not moving/idle?

4) Is the speed good enough for 3D-games and the like?

5) Can it cause lag on non-display-link monitors in a dual or triple monitor setup?

Greetings
Tobi

**Comment by daugustin** [comment]
From my experience:

1 - yes
2 - dont know
3 - Yes. The userspace daemon is taking _a lot_ of cpu.
4 - From my tests the fps dont change when moving the game to a DL screen
5 - For me, yes. Maybe that has something to do with 3.

**Comment by tobimensch** [comment]
@daugustin 

Thanks. Maybe you can test ddcutil.

ddcutil detect #detects connected monitors
ddcutil capabilities #shows you feature codes the monitor supports

with ddcutil detect you can also read out the SN of the monitor.

Then you can:

ddcutil --sn 0123 setvcp 10 0 #this will set the brightness to 0 for the monitor with serial number 0123

10 is the feature code for brightness and might not be the same for your monitor.

You can use the display number and the i2c device bus number instead of the serial number,
but the serial number is unique to the monitor, so I prefer to use it in scripts.

**Comment by Project0** [comment]
`ddcutil detect` does not found any display for me (evdi 1.4.0, Linux 4.11.9-1-ARCH, two display connected via displaylink).

**Comment by tobimensch** [comment]
@Project0 

Thanks!

I request this feature, with little hope.

**Comment by displaylink-mlukaszek** [comment]
I'll clarify some bits before I close.
2 - not at the moment, no.
3 - in general it shouldn't, but this strongly depends on what your windowing system does, what compositor you use does, and what quality of information about "dirty" areas the driver receives because of it. Sometimes all screens are forced to redraw all its contents regardless of which screen actually changes - this is rare, but possible. This can have an effect on both 4 and 5.

A general remark on the CPU usage - if you look at top/htop and alike, make sure you are interpreting the stats with Irix mode off ("i" key in interactive mode toggles it), otherwise the actual full usage of e.g. a 4 core CPU is 400% - and seeing double digit figures of a single process usage is pretty much expected. http://logic.edchen.org/2012/12/how-to-distinguish-differences-on-irix.html
